import { InjuryType, Severity } from "../accidentAndIncidentApi";

export const sampleAccidentData = [
  {
    id: "1",
    referenceNumber: "ACD-8",
    accidentDate: new Date("2024-11-18"),
    accidentTime: new Date("2024-11-26T09:20:00.000Z"),
    severity: Severity.MAJOR,
    division: "Vintage Denim Studio Ltd.",
    department: "Finishing",
    location: "Finishing",
    supervisorName: "Md. Atiyar",
    reportedDate: "2024-11-26",
    orgId: "428cba75",
    evidenceType: "",
    evidenceName: "",
    evidenceId: null,
    status: "Completed",
    assigneeNotification: true,
    resolution: "Completed",
    investigation: null,
    category: "Safety",
    subCategory: "Reportable Injury",
    accidentType: "Other",
    affectedBodyParts: "",
    injuryType: InjuryType.REPORTABLE_ACCIDENT,
    injuryCause: "Overexertion and Repetitive Motion",
    consultedHospital: "BEPZA",
    consultedDoctor: "Md. Faisal",
    timeOfWork: "2 Days",
    returnForWork: null,
    completedNotification: false,
    injury: "Reportable Accident",
    groupNotification: false,
    workPerformed: "<p>Operated Bu machine </p>",
    description:
      '<p>The accident was caused by overexertion and repetitive motion, leading to an injury type of a reportable accident. It has been categorized as an "Other" type of accident falling under the safety category and the sub-category of reportable injury. The incident signifies the importance of proper safety measures and training to prevent such accidents in the future. It serves as a reminder of the need for reporting and addressing all injuries promptly to ensure a safe work environment for all employees.</p>',
    actionTaken:
      "<p>When getting off the machine, it is advised to turn off the machine's switch before proceeding with the work.</p>",
    atmosphereCondition: null,
    lightningCondition: null,
    workSurfaceCondition: null,
    housekeepingCondition: null,
    damage: null,
    disease: null,
    environmental: null,
    training: null,
    lesson: null,
    govReported_date: null,
    esiReported_date: null,
    amount: "0",
    consequenceCategory: "Lost Time,Medical Case,Lost Day",
    returnForWorkHour: null,
    returnForWorkMin: null,
    returnDate: null,
    createdAt: "2024-11-26T10:52:40.245Z",
    updatedAt: "2024-11-27T03:49:03.510Z",
    publishedAt: "2024-11-26T10:52:40.222Z",
    affectedPrimaryRegion: "Upper Limbs",
    affectedSecondaryRegion: "Fingers",
    affectedTertiaryRegion: "Left Fingers",
    rootCause: null,
    assignee: "John Doe",
  },
  {
    id: "2",
    referenceNumber: "ACD-7",
    accidentDate: new Date("2024-11-18"),
    accidentTime: new Date("2024-11-26T09:20:00.000Z"),
    severity: Severity.MAJOR,
    division: "Vintage Denim Studio Ltd.",
    department: "Finishing",
    location: "Finishing",
    supervisorName: "Md. Atiyar",
    reportedDate: "2024-11-26",
    orgId: "428cba75",
    evidenceType: "",
    evidenceName: "",
    evidenceId: null,
    status: "Completed",
    assigneeNotification: true,
    resolution: "Completed",
    investigation: null,
    category: "Safety",
    subCategory: "Reportable Injury",
    accidentType: "Other",
    affectedBodyParts: "",
    injuryType: InjuryType.REPORTABLE_ACCIDENT,
    injuryCause: "Overexertion and Repetitive Motion",
    consultedHospital: "BEPZA",
    consultedDoctor: "Md. Faisal",
    timeOfWork: "2 Days",
    returnForWork: null,
    completedNotification: false,
    injury: "Reportable Accident",
    groupNotification: false,
    workPerformed: "<p>Operated Bu machine </p>",
    description:
      '<p>The accident was caused by overexertion and repetitive motion, leading to an injury type of a reportable accident. It has been categorized as an "Other" type of accident falling under the safety category and the sub-category of reportable injury. The incident signifies the importance of proper safety measures and training to prevent such accidents in the future. It serves as a reminder of the need for reporting and addressing all injuries promptly to ensure a safe work environment for all employees.</p>',
    actionTaken:
      "<p>When getting off the machine, it is advised to turn off the machine's switch before proceeding with the work.</p>",
    atmosphereCondition: null,
    lightningCondition: null,
    workSurfaceCondition: null,
    housekeepingCondition: null,
    damage: null,
    disease: null,
    environmental: null,
    training: null,
    lesson: null,
    govReported_date: null,
    esiReported_date: null,
    amount: "0",
    consequenceCategory: "Lost Time,Medical Case,Lost Day",
    returnForWorkHour: null,
    returnForWorkMin: null,
    returnDate: null,
    createdAt: "2024-11-26T10:52:40.245Z",
    updatedAt: "2024-11-27T03:49:03.510Z",
    publishedAt: "2024-11-26T10:52:40.222Z",
    affectedPrimaryRegion: "Upper Limbs",
    affectedSecondaryRegion: "Fingers",
    affectedTertiaryRegion: "Left Fingers",
    rootCause: null,
    assignee: "John Doe",
  },
];
