// import {
//   ChemicalRequest,
//   ProductStandard,
// } from "../ChemicalManagement/ChemicalRequestApi";

// export const sampleChemicalList = [
//   "Lava FIN U 41",
//   "Aqua Clean X",
//   "Kaya Premium V",
//   "Intense CEL Plus 500",
// ];

// export const sampleChemicalCategoryList = [
//   "Auxiliaries for Enhanced Processing",
//   "Cleaning and Maintenance",
//   "Dyeing Auxiliaries",
//   "Dyes amd Pigments",
//   "Finishing Agents",
//   "Pre-treatment Agents",
//   "Printing Auxiliaries",
//   "Specialty Chemicals",
//   "Others",
// ];

// export const sampleProductStandardList: ProductStandard[] = [
//   {
//     id: "1",
//     name: "ISO 9001",
//   },
//   {
//     id: "2",
//     name: "ISO 14001",
//   },
//   {
//     id: "3",
//     name: "OHSAS 18001",
//   },
//   {
//     id: "4",
//     name: "REACH",
//   },
//   {
//     id: "5",
//     name: "GOTS",
//   },
//   {
//     id: "6",
//     name: "OEKO-TEX",
//   },
// ];

// export const sampleChemicalRequestData: ChemicalRequest[] = [
//   {
//     id: "1",
//     request_date: new Date("2024-10-01"),
//     reference_number: "CHE-32",
//     commercial_name: "Lava FIN U 41",
//     substance_name: "",
//     molecular_formula: "",
//     reach_registration_number: "",
//     zdhc_use_category: "Others",
//     where_and_why_it_is_used: "Wet Process",
//     division: "Vintage Denim Studio Ltd.",
//     requested_customer: "All",
//     requested_merchandiser: "",
//     status: "Approved",
//     modified_date: null,
//     chemical_uuid: "460cd1b4-36d7-4541-ab7c-b6339c1aaa5c",
//     reviewer_remarks: null,
//     approver_remarks: null,
//     reviewer_notification: true,
//     review_status_notification: true,
//     approver_notification: true,
//     approve_status_notification: true,
//     requested_quantity: 73,
//     requested_unit: "KG",
//     createdAt: "2024-11-26T12:16:45.382Z",
//     updatedAt: "2024-11-27T03:18:00.407Z",
//     publishedAt: "2024-11-26T12:16:45.371Z",
//     zdhc_level: "Level-3",
//     cas_no: "Mixture",
//     colour_index: "",
//     use_of_ppe: "Chemical Splash Goggles with Full-Face Shield",
//     hazard_type: "Health Hazards",
//     ghs_classification: "Exclamation",
//     chemical_form_type: "Liquid",
//     product_standard: "",
//     msds_sds_issued_date: null,
//     msds_sds_expiry_date: null,
//     msds_sds: false,
//     created_date: "2024-11-26",
//     approval_valid_date: null,
//     category: null,
//     approver: "Mirza Kausar",
//   },
//   {
//     id: "2",
//     request_date: new Date("2024-09-15"),
//     reference_number: "CHE-33",
//     commercial_name: "Aqua Clean X",
//     substance_name: "Water",
//     molecular_formula: "",
//     reach_registration_number: "",
//     zdhc_use_category: "Others",
//     where_and_why_it_is_used: "Wet Process",
//     division: "Vintage Denim Studio Ltd.",
//     requested_customer: "All",
//     requested_merchandiser: "John Doe",
//     status: "Pending",
//     modified_date: null,
//     chemical_uuid: "123e4567-e89b-12d3-a456-426614174000",
//     reviewer_remarks: null,
//     approver_remarks: null,
//     reviewer_notification: true,
//     review_status_notification: true,
//     approver_notification: true,
//     approve_status_notification: true,
//     requested_quantity: 50,
//     requested_unit: "L",
//     createdAt: "2024-11-20T10:00:00.000Z",
//     updatedAt: "2024-11-21T11:00:00.000Z",
//     publishedAt: "2024-11-20T10:00:00.000Z",
//     zdhc_level: "Level-1",
//     cas_no: "7732-18-5",
//     colour_index: "CI 42090",
//     use_of_ppe: "Gloves and Safety Glasses",
//     hazard_type: "None",
//     ghs_classification: "Non-Hazardous",
//     chemical_form_type: "Liquid",
//     product_standard: "ISO 9001",
//     msds_sds_issued_date: new Date("2024-01-01"),
//     msds_sds_expiry_date: new Date("2025-01-01"),
//     msds_sds: true,
//     created_date: "2024-11-20",
//     approval_valid_date: new Date("2025-01-01"),
//     category: "Cleaning Agents",
//     approver: "John Doe",
//   },
// ];
