import {
  Grievance,
  GrievanceCategory,
  GrievanceChannel,
  GrievancePersonType,
  GrievanceStatus,
  GrievanceType,
} from "../Grievance/grievanceApi";
import { Gender } from "../OccupationalHealth/patientApi";

export const sampleGrievances: Grievance[] = [
  {
    id: 1,
    status: GrievanceStatus.open,
    referenceNumber: "GRV-2025-001",
    personType: GrievancePersonType.employee,
    name: "John Doe",
    gender: Gender.MALE,
    supervisor: "Jane Smith",
    employeeShift: "Day",
    location: "Plant A",
    caseId: "CASE-001",
    type: GrievanceType.complaint,
    submissionDate: new Date("2025-06-01T10:00:00Z"),
    isAnonymous: false,
    channel: GrievanceChannel.email,
    category: GrievanceCategory.hr_management,
    topic: "Workplace harassment",
    submissions: "Submitted to HR",
    description: "Supervisor behavior reported as inappropriate.",
    dueDate: new Date("2025-06-15T00:00:00Z"),
    businessUnit: "Manufacturing",
    resolutionDate: null,
    remarks: "Under investigation",
    helpDeskPerson: "HR Desk 1",
    responsibleDepartment: "HR",
    humanRightsViolation: true,
    scale: "medium",
    frequencyRate: "weekly",
    severityScore: "high",
    committeeStatement: "",
    grievantStatement: "I would like this matter looked into seriously.",
    tradeUnionRepresentative: "Union Rep A",
    isFollowUp: false,
    isAppeal: false,
    solutionProvided: false,
    isIssuesPreviouslyRaised: true,
    statementDocuments: [],
    createdByUserId: "user-100",
    updatedByUserId: "user-100",
    openedByUserId: "user-101",
    inprogressByUserId: "user-102",
    approvedByUserId: null,
    feedback: null,
    stars: null,
    investigationCommitteeStatementDocuments: [],
    evidence: [],
    dateOfJoin: new Date("2020-01-10"),
    servicePeriod: "5 years",
    tenureSplit: "Full-time",
    designation: "Operator",
    department: "Assembly",
    assigneeId: 201,
    respondentDetails: [],
    committeeMemberDetails: [],
    nomineeDetails: [],
    legalAdvisorDetails: [],
  },
  {
    id: 2,
    status: GrievanceStatus.inprogress,
    referenceNumber: "GRV-2025-002",
    personType: GrievancePersonType.contractor,
    name: "Emily Carter",
    gender: Gender.FEMALE,
    supervisor: "Mark Lee",
    employeeShift: "Night",
    location: "Warehouse 3",
    caseId: "CASE-002",
    type: GrievanceType.suggestion,
    submissionDate: new Date("2025-06-10T09:00:00Z"),
    isAnonymous: false,
    channel: GrievanceChannel.digital_grievance_box,
    category: GrievanceCategory.production,
    topic: "Improve packaging process",
    submissions: "Filed via app",
    description: "Suggest adding automated labeling to reduce errors.",
    dueDate: new Date("2025-06-30T00:00:00Z"),
    businessUnit: "Logistics",
    resolutionDate: null,
    remarks: "Under review by engineering",
    helpDeskPerson: null,
    responsibleDepartment: "Production",
    humanRightsViolation: false,
    scale: "low",
    frequencyRate: "one-time",
    severityScore: "low",
    committeeStatement: null,
    grievantStatement: "Hope this idea helps streamline operations.",
    tradeUnionRepresentative: null,
    isFollowUp: false,
    isAppeal: false,
    solutionProvided: false,
    isIssuesPreviouslyRaised: false,
    statementDocuments: [],
    createdByUserId: "user-103",
    updatedByUserId: "user-103",
    openedByUserId: "user-103",
    inprogressByUserId: "user-104",
    approvedByUserId: null,
    feedback: null,
    stars: null,
    investigationCommitteeStatementDocuments: [],
    evidence: [],
    dateOfJoin: new Date("2023-03-01"),
    servicePeriod: "1 year 3 months",
    tenureSplit: "Contractor",
    designation: "Packager",
    department: "Packaging",
    assigneeId: 203,
    respondentDetails: [],
    committeeMemberDetails: [],
    nomineeDetails: [],
    legalAdvisorDetails: [],
  },
  {
    id: 3,
    status: GrievanceStatus.completed,
    referenceNumber: "GRV-2025-003",
    personType: GrievancePersonType.visitor,
    name: "Ali Khan",
    gender: Gender.MALE,
    supervisor: "",
    employeeShift: "",
    location: "Main Gate",
    caseId: "CASE-003",
    type: GrievanceType.question,
    submissionDate: new Date("2025-05-20T14:00:00Z"),
    isAnonymous: true,
    channel: GrievanceChannel.grievance_box,
    category: GrievanceCategory.others,
    topic: "Visitor entry policy",
    submissions: "Dropped in box anonymously",
    description: "Can visitors carry electronic items inside the plant?",
    dueDate: new Date("2025-05-25T00:00:00Z"),
    businessUnit: "Security",
    resolutionDate: new Date("2025-05-23T00:00:00Z"),
    remarks: "Clarification posted at gate",
    helpDeskPerson: "Security Desk",
    responsibleDepartment: "Security",
    humanRightsViolation: false,
    scale: "N/A",
    frequencyRate: "N/A",
    severityScore: "N/A",
    committeeStatement: "Not applicable",
    grievantStatement: "",
    tradeUnionRepresentative: null,
    isFollowUp: false,
    isAppeal: false,
    solutionProvided: true,
    isIssuesPreviouslyRaised: false,
    statementDocuments: [],
    createdByUserId: "user-110",
    updatedByUserId: "user-110",
    openedByUserId: "user-111",
    inprogressByUserId: "user-111",
    approvedByUserId: "user-112",
    feedback: "Thanks for the prompt action.",
    stars: 4,
    investigationCommitteeStatementDocuments: [],
    evidence: [],
    dateOfJoin: null,
    servicePeriod: null,
    tenureSplit: null,
    designation: null,
    department: null,
    assigneeId: null,
    respondentDetails: [],
    committeeMemberDetails: [],
    nomineeDetails: [],
    legalAdvisorDetails: [],
  },
];
