export const sampleInternalAuditData = [
  {
    id: "1",
    referenceNumber: "AUD-8",
    auditDate: new Date("2024-11-18"),
    dateApproval: new Date("2024-11-26T09:20:00.000Z"),
    division: "Vintage Denim Studio Ltd.",
    department: "Finishing",
    auditLocation: "Finishing",
    auditTitle: "Social Audit",
    auditType: "Company",
    factoryName: "ABBA",
    factoryAddress: "Bangladesh",
    factoryContact: "071 2369858",
    designation: "Manager",
    email: "sattva@gmail.com",
    contactNumber: "081 2304825",
    description: "This is Internal Audit",
    auditee: "John Doe",
    approver: "John Cena",
    auditStatus: 20,
  },
  {
    id: "2",
    referenceNumber: "AUD-9",
    auditDate: new Date("2024-11-18"),
    dateApproval: new Date("2024-11-26T09:20:00.000Z"),
    division: "Vintage Denim Studio Ltd.",
    department: "Finishing",
    auditLocation: "Finishing",
    auditTitle: "Social Audit",
    auditType: "Company",
    factoryName: "ABBAs",
    factoryAddress: "Bangladesh",
    factoryContact: "071 2369858",
    designation: "Manager",
    email: "sattva@gmail.com",
    contactNumber: "081 2304825",
    description: "This is Internal Audit",
    auditee: "John Doe",
    approver: "John Khali",
    auditStatus: 60,
  },
];
