import { MedicineInventory } from "../OccupationalHealth/medicineInventoryApi";

export const medicineInventoryForms = [
  "Injection",
  "Suppository",
  "Patch",
  "Inhaler",
  "Cream/Gel/Ointment",
  "Drops",
  "Suspension",
  "Liquid Syrup",
  "Capsule",
  "Tablet",
];

export const supplierTypes = [
  "Agent",
  "Manufacturer",
  "Distributor",
  "Supplier",
];

export const medicineTypes = [
  "First Aid",
  "Prescription",
  "Over the Counter",
  "Vaccination",
];

export const sampleMedicineSuppliers = [
  {
    id: "1",
    supplierName: "Pharma Supplier",
    supplier_contact_number: "1234567890",
    supplier_email_id: "sample@gma.cc",
  },
  {
    id: "2",
    supplierName: "HealthCare Ltd.",
    supplierContactNumber: "0987654321",
    supplierEmail: "sss@faa.daw",
  },
];

export const medicineInventorySampleData: MedicineInventory[] = [
  {
    id: "1",
    medicineName: "Xorol 20mg",
    genericName: "Acidity",
    division: "Vintage Denim Studio Ltd.",
    dosageStrength: null,
    expiryDate: null,
    form: null,
    manufacturerName: null,
    supplierName: null,
    supplierContactNumber: null,
    supplierEmail: null,
    supplierType: null,
    location: null,
    manufacturingDate: null,
    deliveryDate: null,
    deliveryUnit: null,
    purchaseAmount: null,
    thresholdLimit: null,
    invoiceDate: null,
    invoiceReference: null,
    batchNumber: null,
    unitCost: null,
    reorderThreshold: null,
    usageInstruction: null,
    deliveryQuantity: null,
    issuedQuantity: null,
    disposedOfQuantity: null,
    balanceQuantity: null,
    approverRemarks: "",
    referenceNumber: "MED-1",
    requestedDate: "2024-11-23",
    status: "Approved",
    requestedQuantity: 400,
    medicineUuid: "b28a5dd2-f07d-4d86-9ace-c79159851337",
    purchaseNotification: true,
    created_at: "2024-11-25T05:00:03.867Z",
    updated_at: "2024-11-25T05:01:00.576Z",
    publishedAt: "2024-11-25T05:00:03.847Z",
    medicineType: null,
    approver: null,
    reporter: null,
    medicineDisposals: null,
    businessUnit: null,
    requestedBy: "John Doe",
    approvedBy: "Jane Doe",
  },
  {
    id: "2",
    medicineName: "Paracetamol 500mg",
    genericName: "Pain Relief",
    division: "HealthCare Ltd.",
    dosageStrength: "500mg",
    expiryDate: new Date("2025-12-31"),
    form: "Tablet",
    manufacturerName: "HealthCare Ltd.",
    supplierName: "Pharma Supplier",
    supplierContactNumber: "1234567890",
    supplierEmail: "supplier@example.com",
    supplierType: "Distributor",
    location: "Warehouse A",
    manufacturingDate: new Date("2023-01-01"),
    deliveryDate: new Date("2023-01-15"),
    deliveryUnit: "Box",
    purchaseAmount: "1000",
    thresholdLimit: "100",
    invoiceDate: new Date("2023-01-16"),
    invoiceReference: "INV-12345",
    batchNumber: "BATCH-001",
    unitCost: "0.50",
    reorderThreshold: "200",
    usageInstruction: "Take one tablet every 6 hours",
    deliveryQuantity: "2000",
    issuedQuantity: "1500",
    disposedOfQuantity: "100",
    balanceQuantity: "400",
    approverRemarks: "Approved for use",
    referenceNumber: "MED-2",
    requestedDate: "2024-11-23",
    status: "Approved",
    requestedQuantity: 500,
    medicineUuid: "a12b3c4d-5e6f-7g8h-9i0j-k1l2m3n4o5p6",
    purchaseNotification: true,
    created_at: "2024-11-25T05:00:03.867Z",
    updated_at: "2024-11-25T05:01:00.576Z",
    publishedAt: "2024-11-25T05:00:03.847Z",
    medicineType: "Tablet",
    approver: null,
    reporter: null,
    medicineDisposals: null,
    businessUnit: null,
    requestedBy: "John Doe",
    approvedBy: "Jane Doe",
  },
];
