import { MedicineInventory } from "../OccupationalHealth/medicineInventoryApi";

export const medicineInventoryForms = [
  "Injection",
  "Suppository",
  "Patch",
  "Inhaler",
  "Cream/Gel/Ointment",
  "Drops",
  "Suspension",
  "Liquid Syrup",
  "Capsule",
  "Tablet",
];

export const supplierTypes = [
  "Agent",
  "Manufacturer",
  "Distributor",
  "Supplier",
];

export const medicineTypes = [
  "First Aid",
  "Prescription",
  "Over the Counter",
  "Vaccination",
];

export const sampleMedicineSuppliers = [
  {
    id: "1",
    supplier_name: "Pharma Supplier",
    supplier_contact_number: "1234567890",
    supplier_email_id: "sample@gma.cc",
  },
  {
    id: "2",
    supplier_name: "HealthCare Ltd.",
    supplier_contact_number: "0987654321",
    supplier_email_id: "sss@faa.daw",
  },
];

export const medicineInventorySampleData: MedicineInventory[] = [
  {
    id: "1",
    medicine_name: "Xorol 20mg",
    generic_name: "Acidity",
    division: "Vintage Denim Studio Ltd.",
    dosage_strength: null,
    expiry_date: null,
    form: null,
    manufacturer_name: null,
    supplier_name: null,
    supplier_contact_number: null,
    supplier_email_id: null,
    supplier_type: null,
    location: null,
    manufacturing_date: null,
    delivery_date: null,
    delivered_unit: null,
    purchased_amount: null,
    threshold_limit: null,
    invoice_date: null,
    invoice_reference: null,
    batch_number: null,
    unit_cost: null,
    reorder_threshold: null,
    usage_instructions: null,
    delivered_quantity: null,
    issued_quantity: null,
    disposed_of_quantity: null,
    balance_quantity: null,
    approver_remarks: "",
    reference_number: "MED-1",
    request_date: "2024-11-23",
    status: "Approved",
    requested_quantity: 400,
    medicine_uuid: "b28a5dd2-f07d-4d86-9ace-c79159851337",
    purchase_notification: true,
    createdAt: "2024-11-25T05:00:03.867Z",
    updatedAt: "2024-11-25T05:01:00.576Z",
    publishedAt: "2024-11-25T05:00:03.847Z",
    medicine_type: null,
    approver: null,
    reporter: null,
    medicine_disposals: null,
    business_unit: null,
    requested_by: "John Doe",
    approved_by: "Jane Doe",
  },
  {
    id: "2",
    medicine_name: "Paracetamol 500mg",
    generic_name: "Pain Relief",
    division: "HealthCare Ltd.",
    dosage_strength: "500mg",
    expiry_date: new Date("2025-12-31"),
    form: "Tablet",
    manufacturer_name: "HealthCare Ltd.",
    supplier_name: "Pharma Supplier",
    supplier_contact_number: "1234567890",
    supplier_email_id: "supplier@example.com",
    supplier_type: "Distributor",
    location: "Warehouse A",
    manufacturing_date: new Date("2023-01-01"),
    delivery_date: new Date("2023-01-15"),
    delivered_unit: "Box",
    purchased_amount: "1000",
    threshold_limit: "100",
    invoice_date: new Date("2023-01-16"),
    invoice_reference: "INV-12345",
    batch_number: "BATCH-001",
    unit_cost: "0.50",
    reorder_threshold: "200",
    usage_instructions: "Take one tablet every 6 hours",
    delivered_quantity: "2000",
    issued_quantity: "1500",
    disposed_of_quantity: "100",
    balance_quantity: "400",
    approver_remarks: "Approved for use",
    reference_number: "MED-2",
    request_date: "2024-11-23",
    status: "Approved",
    requested_quantity: 500,
    medicine_uuid: "a12b3c4d-5e6f-7g8h-9i0j-k1l2m3n4o5p6",
    purchase_notification: true,
    createdAt: "2024-11-25T05:00:03.867Z",
    updatedAt: "2024-11-25T05:01:00.576Z",
    publishedAt: "2024-11-25T05:00:03.847Z",
    medicine_type: "Tablet",
    approver: null,
    reporter: null,
    medicine_disposals: null,
    business_unit: null,
    requested_by: "John Doe",
    approved_by: "Jane Doe",
  },
];
