import {
  Designation,
  Doctor,
  Gender,
  Patient,
  WorkStatus,
} from "../OccupationalHealth/patientApi";

export const sampleDoctorData: Doctor[] = [
  {
    id: "doc_1",
    first_name: "John",
    last_name: "Doe",
    designation: "Doctor",
    org_id: "ORG001",
    email: "samplemail@gmail.com",
    escalate_email: "esk@gmail.com",
    hse_head: true,
    gender: "male",
    employee_id: "EMP001",
    chairperson: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    birth_date: new Date(),
    corporate_user: true,
    weekly_report: true,
  },
  {
    id: "doc_2",
    first_name: "Jane",
    last_name: "Doe",
    designation: "Doctor",
    org_id: "ORG002",
    email: "sss@gg.com",
    escalate_email: "saww@ffa.com",
    hse_head: true,
    gender: "male",
    employee_id: "EMP003",
    chairperson: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    birth_date: new Date(),
    corporate_user: true,
    weekly_report: true,
  },
];

export const samplePatientData: Patient[] = [
  {
    id: "1",
    employee_name: "John Doe",
    employee_id: "EMP001",
    designation: Designation.DRY_PROCESS_TECHNICIAN,
    gender: Gender.MALE,
    department: "Engineering",
    age: 30,
    sub_department: "Software Development",
    symptoms: "Fever, Cough, Headache",
    check_in: new Date(),
    check_out: new Date(),
    time_spent: 30,
    body_temperature: 37.5,
    weight: 70,
    severity_level: 2,
    treatment: "Paracetamol, Rest",
    disease: "Common Cold",
    patient_status: "Discharged",
    follow_up_date: new Date(),
    blood_pressure: "120/80",
    division: "Software Development",
    clinic_division: "Clinical Suite",
    follow_up_status: true,
    medicine_status: "Prescribed",
    height: 180,
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    check_in_date: new Date(),
    check_out_date: new Date(),
    random_blood_sugar: "120",
    hospital_name: "Hospital A",
    hospital_location: "Location A",
    doctor_prescription: "Paracetamol 500mg",
    admitted_date: new Date(),
    discharged_date: new Date(),
    sent_via_ambulance: "Yes",
    refer_to_another_hospital: "No",
    since_complaint: "2 days",
    recommended_duration: "3 days",
    lift_usage_required: "Yes",
    work_status: WorkStatus.ON_DUTY,
    consulting_doctor:
      sampleDoctorData[0]?.first_name + " " + sampleDoctorData[0]?.last_name,
    status: "Pending",
    createdBy: "John Doe",
  },
  {
    id: "2",
    employee_name: "John dae",
    employee_id: "EMP001",
    designation: Designation.DRY_PROCESS_TECHNICIAN,
    gender: Gender.FEMALE,
    department: "Engineering",
    age: 30,
    sub_department: "Software Development",
    symptoms: "Fever, Cough, Headache",
    check_in: new Date(),
    check_out: new Date(),
    time_spent: 30,
    body_temperature: 37.5,
    weight: 70,
    severity_level: 2,
    treatment: "Paracetamol, Rest",
    disease: "Common Cold",
    patient_status: "Discharged",
    follow_up_date: new Date(),
    blood_pressure: "120/80",
    division: "Software Development",
    clinic_division: "Clinical Suite",
    follow_up_status: true,
    medicine_status: "Prescribed",
    height: 180,
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    check_in_date: new Date(),
    check_out_date: new Date(),
    random_blood_sugar: "120",
    hospital_name: "Hospital A",
    hospital_location: "Location A",
    doctor_prescription: "Paracetamol 500mg",
    admitted_date: new Date(),
    discharged_date: new Date(),
    sent_via_ambulance: "Yes",
    refer_to_another_hospital: "No",
    since_complaint: "2 days",
    recommended_duration: "3 days",
    lift_usage_required: "Yes",
    work_status: WorkStatus.ON_DUTY,
    consulting_doctor:
      sampleDoctorData[1]?.first_name + " " + sampleDoctorData[1]?.last_name,
    status: "Pending",
    createdBy: "John Doe",
  },
];
