import {
  Designation,
  Doctor,
  Gender,
  Patient,
  WorkStatus,
} from "../OccupationalHealth/patientApi";

export const sampleDoctorData: Doctor[] = [
  {
    id: "doc_1",
    first_name: "John",
    last_name: "Doe",
    designation: "Doctor",
    org_id: "ORG001",
    email: "samplemail@gmail.com",
    escalate_email: "esk@gmail.com",
    hse_head: true,
    gender: "male",
    employee_id: "EMP001",
    chairperson: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    birth_date: new Date(),
    corporate_user: true,
    weekly_report: true,
  },
  {
    id: "doc_2",
    first_name: "Jane",
    last_name: "Doe",
    designation: "Doctor",
    org_id: "ORG002",
    email: "sss@gg.com",
    escalate_email: "saww@ffa.com",
    hse_head: true,
    gender: "male",
    employee_id: "EMP003",
    chairperson: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    birth_date: new Date(),
    corporate_user: true,
    weekly_report: true,
  },
];

export const samplePatientData: Patient[] = [
  {
    id: "1",
    employeeName: "John Doe",
    employeeId: "EMP001",
    designation: Designation.DRY_PROCESS_TECHNICIAN,
    gender: Gender.MALE,
    department: "Engineering",
    age: 30,
    subDepartment: "Software Development",
    symptoms: "Fever, Cough, Headache",
    checkInDate: new Date(),
    checkOut: new Date(),
    timeSpent: 30,
    bodyTemperature: 37.5,
    weight: 70,
    severityLevel: 2,
    treatment: "Paracetamol, Rest",
    disease: "Common Cold",
    patientStatus: "Discharged",
    followUpDate: new Date(),
    bloodPressure: "120/80",
    division: "Software Development",
    clinicDivision: "Clinical Suite",
    followUpStatus: true,
    medicineStatus: "Prescribed",
    height: 180,
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    checkOutDate: new Date(),
    randomBloodSugar: "120",
    hospitalName: "Hospital A",
    hospitalLocation: "Location A",
    doctorPrescription: "Paracetamol 500mg",
    admittedDate: new Date(),
    dischargedDate: new Date(),
    sentViaAmbulance: "Yes",
    referToAnotherHospital: "No",
    sinceComplaint: "2 days",
    recommendedDuration: "3 days",
    liftUsageRequired: "Yes",
    workStatus: WorkStatus.ON_DUTY,
    consultingDoctor:
      sampleDoctorData[0]?.first_name + " " + sampleDoctorData[0]?.last_name,
    status: "Pending",
    createdBy: "John Doe",
  },
  {
    id: "2",
    employeeName: "John Dae",
    employeeId: "EMP001",
    designation: Designation.DRY_PROCESS_TECHNICIAN,
    gender: Gender.FEMALE,
    department: "Engineering",
    age: 30,
    subDepartment: "Software Development",
    symptoms: "Fever, Cough, Headache",
    checkInDate: new Date(),
    checkOut: new Date(),
    timeSpent: 30,
    bodyTemperature: 37.5,
    weight: 70,
    severityLevel: 2,
    treatment: "Paracetamol, Rest",
    disease: "Common Cold",
    patientStatus: "Discharged",
    followUpDate: new Date(),
    bloodPressure: "120/80",
    division: "Software Development",
    clinicDivision: "Clinical Suite",
    followUpStatus: true,
    medicineStatus: "Prescribed",
    height: 180,
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    checkOutDate: new Date(),
    randomBloodSugar: "120",
    hospitalName: "Hospital A",
    hospitalLocation: "Location A",
    doctorPrescription: "Paracetamol 500mg",
    admittedDate: new Date(),
    dischargedDate: new Date(),
    sentViaAmbulance: "Yes",
    referToAnotherHospital: "No",
    sinceComplaint: "2 days",
    recommendedDuration: "3 days",
    liftUsageRequired: "Yes",
    workStatus: WorkStatus.ON_DUTY,
    consultingDoctor:
      sampleDoctorData[1]?.first_name + " " + sampleDoctorData[1]?.last_name,
    status: "Pending",
    createdBy: "John Doe",
  },
];
