import { z } from "zod";
import axios from "axios";

export const attritionSchema = z.object({
  id: z.string(),
  referenceNumber: z.string(),
  employeeName: z.string(),
  employeeId: z.string(),
  gender: z.string(),
  countryName: z.string(),
  state: z.string(),
  resignedDate: z.date(),
  relievedDate: z.date(),
  division: z.string(), 
  designation: z.string(),
  department: z.string(),
  perDaySalary: z.number(),
  dateOfJoin: z.date(),
  employmentClassification: z.string(),
  employmentType: z.string(),
  isHostelAccess: z.boolean(),
  isWorkHistory: z.boolean(),
  resignationType: z.string(),
  resignationReason: z.string(),
  servicePeriod: z.string(),
  tenureSplit: z.string(),
  isNormalResignation: z.boolean(),
  remark: z.string(),
  status: z.string(),
  createdByUser: z.number(),
  updatedBy: z.number(),
  completeBy: z.number(),
});

export type Attrition = z.infer<typeof attritionSchema>;

export async function fetchDivision() {
  const res = await axios.get("/api/hr-divisions");
  return res.data;
}

export const attritionData = [
    {
      id: "1",
      referenceNumber: "RAG-01",
      employeeName: "Akila Manujith",
      employeeId: "FAE-02",
      gender: "Male",
      countryName: "Sri Lanka",
      state: "Kandy",
      dateOfJoin: new Date("2023-12-31"),
      resignedDate: new Date("2023-12-31"),
      relievedDate: new Date("2023-12-31"),
      division: "Vintage Denim Pvt (Ltd.)",
      designation: "Team Manager",
      department: "Kandy",
      perDaySalary: 25000.00,
      employmentClassification: "Manager",
      employmentType: "Full-Time",
      isHostelAccess: true,
      isWorkHistory: false,
      resignationType: "Retirement",
      resignationReason: "Over Date",
      servicePeriod: "35 Years",
      tenureSplit: "4-5 Years",
      isNormalResignation: true,
      remark: "OK",
      status: "Announced",
      createdByUser: 2,
      updatedBy: 4,
      completeBy: 5,
    },
    {
      id: "2",
      referenceNumber: "RAG-02",
      employeeName: "Nimasha Perera",
      employeeId: "FAE-05",
      gender: "Female",
      countryName: "Sri Lanka",
      state: "Colombo",
      dateOfJoin: new Date("2023-12-31"),
  
      resignedDate: new Date("2024-03-15"),
      relievedDate: new Date("2024-04-01"),
      division: "Vintage Apparel Co.",
      designation: "HR Executive",
      department: "Human Resources",
      perDaySalary: 18000.00,
      employmentClassification: "Executive",
      employmentType: "Full-Time",
      isHostelAccess: false,
      isWorkHistory: true,
      resignationType: "Voluntary",
      resignationReason: "Personal Reasons",
      servicePeriod: "5 Years",
      tenureSplit: "2-3 Years",
      isNormalResignation: true,
      remark: "Exit interview completed",
      status: "Processing",
      createdByUser: 3,
      updatedBy: 3,
      completeBy: 7,
    },
    {
      id: "3",
      referenceNumber: "RAG-03",
      employeeName: "Sahan Fernando",
      employeeId: "FAE-12",
      gender: "Male",
      countryName: "Sri Lanka",
      state: "Galle",
      dateOfJoin: new Date("2023-12-31"),
  
      resignedDate: new Date("2024-01-10"),
      relievedDate: new Date("2024-01-31"),
      division: "Denim Designers Ltd.",
      designation: "Software Engineer",
      department: "IT",
      perDaySalary: 22000.00,
      employmentClassification: "Technical",
      employmentType: "Contract",
      isHostelAccess: false,
      isWorkHistory: true,
      resignationType: "Termination",
      resignationReason: "Performance Issues",
      servicePeriod: "1.5 Years",
      tenureSplit: "<2 Years",
      isNormalResignation: false,
      remark: "No further action required",
      status: "Completed",
      createdByUser: 1,
      updatedBy: 2,
      completeBy: 2,
    },
    {
      id: "4",
      referenceNumber: "RAG-04",
      employeeName: "Tharindu Jayasuriya",
      employeeId: "FAE-09",
      gender: "Male",
      countryName: "Sri Lanka",
      state: "Kurunegala",
      dateOfJoin: new Date("2023-12-31"),
  
      resignedDate: new Date("2023-11-20"),
      relievedDate: new Date("2023-11-30"),
      division: "Vintage Denim Pvt (Ltd.)",
      designation: "Line Supervisor",
      department: "Production",
      perDaySalary: 15000.00,
      employmentClassification: "Supervisor",
      employmentType: "Full-Time",
      isHostelAccess: true,
      isWorkHistory: true,
      resignationType: "Voluntary",
      resignationReason: "Family Relocation",
      servicePeriod: "10 Years",
      tenureSplit: "6-10 Years",
      isNormalResignation: true,
      remark: "Cleared",
      status: "Approved",
      createdByUser: 4,
      updatedBy: 4,
      completeBy: 4,
    },
  ];

  export const createDesignation = async (designation: string) => {
    const res = await axios.post("/api/designation", designation);
    console.log(designation);
    return res.data;
  };