import { z } from "zod";

export const PermissionSectionsMap: PermissionSection[] = [
  {
    mainSection: "Main",
    subSections: [
      {
        name: "Insight",
        key: "INSIGHT",
        permissionsExists: {
          VIEW: true,
          CREATE: false,
          EDIT: false,
          DELETE: false,
        },
      },
    ],
  },
  {
    mainSection: "Sustainability Apps",
    subSections: [
      {
        break: true,
        name: "Audit & Inspection",
      },
      {
        name: "Dashboard",
        key: "AUDIT_INSPECTION_DASHBOARD",
        permissionsExists: {
          VIEW: true,
          CREATE: false,
          EDIT: false,
          DELETE: false,
        },
      },
      {
        name: "Calendar",
        key: "AUDIT_INSPECTION_CALENDAR",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Internal Audit > Register",
        key: "AUDIT_INSPECTION_INTERNAL_AUDIT_REGISTER",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Internal Audit > Task",
        key: "AUDIT_INSPECTION_INTERNAL_AUDIT_TASK",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Internal Audit > Queue",
        key: "AUDIT_INSPECTION_INTERNAL_AUDIT_QUEUE",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Internal Audit > Corrective Action",
        key: "AUDIT_INSPECTION_INTERNAL_AUDIT_CORRECTIVE_ACTION",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "External Audit > Register",
        key: "AUDIT_INSPECTION_EXTERNAL_AUDIT_REGISTER",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "External Audit > Task",
        key: "AUDIT_INSPECTION_EXTERNAL_AUDIT_TASK",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "External Audit > Queue",
        key: "AUDIT_INSPECTION_EXTERNAL_AUDIT_QUEUE",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "External Audit > Corrective Action",
        key: "AUDIT_INSPECTION_EXTERNAL_AUDIT_CORRECTIVE_ACTION",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        break: true,
        name: "Sustainability",
      },
      {
        name: "SDG Reporting",
        key: "SUSTAINABILITY_SDG_REPORTING",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        break: true,
        name: "Environment",
      },
      {
        name: "Dashboard",
        key: "ENVIRONMENT_DASHBOARD",
        permissionsExists: {
          VIEW: true,
          CREATE: false,
          EDIT: false,
          DELETE: false,
        },
      },
      {
        name: "History > Consumption",
        key: "ENVIRONMENT_HISTORY_CONSUMPTION",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "History > Target Setting",
        key: "ENVIRONMENT_HISTORY_TARGET_SETTING",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Assigned Tasks > Consumption",
        key: "ENVIRONMENT_ASSIGNED_TASKS_CONSUMPTION",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Assigned Tasks > Target Setting",
        key: "ENVIRONMENT_ASSIGNED_TASKS_TARGET_SETTING",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        break: true,
        name: "Chemical MNG",
      },
      {
        name: "Dashboard",
        key: "CHEMICAL_MNG_DASHBOARD",
        permissionsExists: {
          VIEW: true,
          CREATE: false,
          EDIT: false,
          DELETE: false,
        },
      },
      {
        name: "Request Register",
        key: "CHEMICAL_MNG_REQUEST_REGISTER",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Purchase & Inventory",
        key: "CHEMICAL_MNG_PURCHASE_INVENTORY",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Transaction",
        key: "CHEMICAL_MNG_TRANSACTION",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Assigned Tasks",
        key: "CHEMICAL_MNG_ASSIGNED_TASKS",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
    ],
  },
  {
    mainSection: "Health & Safety Apps",
    subSections: [
      {
        name: "Hazard & Risk > Dashboard",
        key: "HAZARD_RISK_DASHBOARD",
        permissionsExists: {
          VIEW: true,
          CREATE: false,
          EDIT: false,
          DELETE: false,
        },
      },
      {
        name: "Hazard & Risk > Register",
        key: "HAZARD_RISK_REGISTER",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Hazard & Risk > Assigned Tasks",
        key: "HAZARD_RISK_ASSIGNED_TASKS",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        break: true,
        name: "Incident & Accident",
      },
      {
        name: "Dashboard",
        key: "INCIDENT_ACCIDENT_DASHBOARD",
        permissionsExists: {
          VIEW: true,
          CREATE: false,
          EDIT: false,
          DELETE: false,
        },
      },
      {
        name: "Register",
        key: "INCIDENT_ACCIDENT_REGISTER",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Assigned Tasks",
        key: "INCIDENT_ACCIDENT_ASSIGNED_TASKS",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        break: true,
        name: "Document",
      },
      {
        name: "Register",
        key: "DOCUMENT_REGISTER",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        break: true,
        name: "Occupational Health",
      },
      {
        name: "Dashboard",
        key: "OCCUPATIONAL_HEALTH_DASHBOARD",
        permissionsExists: {
          VIEW: true,
          CREATE: false,
          EDIT: false,
          DELETE: false,
        },
      },
      {
        name: "Clinical Suite > Patient Register",
        key: "OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PATIENT_REGISTER",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Clinical Suite > Consultation",
        key: "OCCUPATIONAL_HEALTH_CLINICAL_SUITE_CONSULTATION",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Clinical Suite > Medicine Stock",
        key: "OCCUPATIONAL_HEALTH_CLINICAL_SUITE_MEDICINE_STOCK",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Clinical Suite > Pharmacy Queue",
        key: "OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PHARMACY_QUEUE",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Medicine Inventory > Medicine Request",
        key: "OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_MEDICINE_REQUEST",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Medicine Inventory > Purchase & Inventory",
        key: "OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_PURCHASE_INVENTORY",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Medicine Inventory > Transaction",
        key: "OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_TRANSACTION",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Medicine Inventory > Assigned Tasks",
        key: "OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_ASSIGNED_TASKS",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
    ],
  },
  {
    mainSection: "Social Apps",
    subSections: [
      {
        name: "Grievance > Dashboard",
        key: "GRIEVANCE_DASHBOARD",
        permissionsExists: {
          VIEW: true,
          CREATE: false,
          EDIT: false,
          DELETE: false,
        },
      },
      {
        name: "Grievance > Register",
        key: "GRIEVANCE_REGISTER",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Grievance > Assigned Tasks",
        key: "GRIEVANCE_ASSIGNED_TASKS",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        break: true,
        name: "RAG",
      },
      {
        name: "Dashboard",
        key: "RAG_DASHBOARD",
        permissionsExists: {
          VIEW: true,
          CREATE: false,
          EDIT: false,
          DELETE: false,
        },
      },
      {
        name: "Register",
        key: "RAG_REGISTER",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        name: "Assigned Tasks",
        key: "RAG_ASSIGNED_TASKS",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        break: true,
        name: "Engagement",
      },
      {
        name: "Register",
        key: "ENGAGEMENT_REGISTER",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
      {
        break: true,
        name: "Attrition",
      },
      {
        name: "Register",
        key: "ATTRITION_REGISTER",
        permissionsExists: {
          VIEW: true,
          CREATE: true,
          EDIT: true,
          DELETE: true,
        },
      },
    ],
  },
];

export interface PermissionSection {
  mainSection: string;
  subSections: SubSection[];
}

export interface SubSectionWithPermissions {
  name: string;
  key: string;
  permissionsExists: PermissionsExists;
}

export interface SubSectionBreak {
  break: boolean;
  name: string;
}

export type SubSection = SubSectionWithPermissions | SubSectionBreak;

export interface PermissionsExists {
  VIEW: boolean;
  CREATE: boolean;
  EDIT: boolean;
  DELETE: boolean;
}

export const PermissionKeysObjectSchema = z.object({
  INSIGHT_VIEW: z.boolean(),
  AUDIT_INSPECTION_DASHBOARD_VIEW: z.boolean(),
  AUDIT_INSPECTION_CALENDAR_VIEW: z.boolean(),
  AUDIT_INSPECTION_CALENDAR_CREATE: z.boolean(),
  AUDIT_INSPECTION_CALENDAR_EDIT: z.boolean(),
  AUDIT_INSPECTION_CALENDAR_DELETE: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_REGISTER_VIEW: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_REGISTER_CREATE: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_REGISTER_EDIT: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_REGISTER_DELETE: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_TASK_VIEW: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_TASK_CREATE: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_TASK_EDIT: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_TASK_DELETE: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_QUEUE_VIEW: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_QUEUE_CREATE: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_QUEUE_EDIT: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_QUEUE_DELETE: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_CORRECTIVE_ACTION_VIEW: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_CORRECTIVE_ACTION_CREATE: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_CORRECTIVE_ACTION_EDIT: z.boolean(),
  AUDIT_INSPECTION_INTERNAL_AUDIT_CORRECTIVE_ACTION_DELETE: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_REGISTER_VIEW: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_REGISTER_CREATE: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_REGISTER_EDIT: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_REGISTER_DELETE: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_TASK_VIEW: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_TASK_CREATE: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_TASK_EDIT: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_TASK_DELETE: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_QUEUE_VIEW: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_QUEUE_CREATE: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_QUEUE_EDIT: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_QUEUE_DELETE: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_CORRECTIVE_ACTION_VIEW: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_CORRECTIVE_ACTION_CREATE: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_CORRECTIVE_ACTION_EDIT: z.boolean(),
  AUDIT_INSPECTION_EXTERNAL_AUDIT_CORRECTIVE_ACTION_DELETE: z.boolean(),
  SUSTAINABILITY_SDG_REPORTING_VIEW: z.boolean(),
  SUSTAINABILITY_SDG_REPORTING_CREATE: z.boolean(),
  SUSTAINABILITY_SDG_REPORTING_EDIT: z.boolean(),
  SUSTAINABILITY_SDG_REPORTING_DELETE: z.boolean(),
  ENVIRONMENT_DASHBOARD_VIEW: z.boolean(),
  ENVIRONMENT_HISTORY_CONSUMPTION_VIEW: z.boolean(),
  ENVIRONMENT_HISTORY_CONSUMPTION_CREATE: z.boolean(),
  ENVIRONMENT_HISTORY_CONSUMPTION_EDIT: z.boolean(),
  ENVIRONMENT_HISTORY_CONSUMPTION_DELETE: z.boolean(),
  ENVIRONMENT_HISTORY_TARGET_SETTING_VIEW: z.boolean(),
  ENVIRONMENT_HISTORY_TARGET_SETTING_CREATE: z.boolean(),
  ENVIRONMENT_HISTORY_TARGET_SETTING_EDIT: z.boolean(),
  ENVIRONMENT_HISTORY_TARGET_SETTING_DELETE: z.boolean(),
  ENVIRONMENT_ASSIGNED_TASKS_CONSUMPTION_VIEW: z.boolean(),
  ENVIRONMENT_ASSIGNED_TASKS_CONSUMPTION_CREATE: z.boolean(),
  ENVIRONMENT_ASSIGNED_TASKS_CONSUMPTION_EDIT: z.boolean(),
  ENVIRONMENT_ASSIGNED_TASKS_CONSUMPTION_DELETE: z.boolean(),
  ENVIRONMENT_ASSIGNED_TASKS_TARGET_SETTING_VIEW: z.boolean(),
  ENVIRONMENT_ASSIGNED_TASKS_TARGET_SETTING_CREATE: z.boolean(),
  ENVIRONMENT_ASSIGNED_TASKS_TARGET_SETTING_EDIT: z.boolean(),
  ENVIRONMENT_ASSIGNED_TASKS_TARGET_SETTING_DELETE: z.boolean(),
  CHEMICAL_MNG_DASHBOARD_VIEW: z.boolean(),
  CHEMICAL_MNG_REQUEST_REGISTER_VIEW: z.boolean(),
  CHEMICAL_MNG_REQUEST_REGISTER_CREATE: z.boolean(),
  CHEMICAL_MNG_REQUEST_REGISTER_EDIT: z.boolean(),
  CHEMICAL_MNG_REQUEST_REGISTER_DELETE: z.boolean(),
  CHEMICAL_MNG_PURCHASE_INVENTORY_VIEW: z.boolean(),
  CHEMICAL_MNG_PURCHASE_INVENTORY_CREATE: z.boolean(),
  CHEMICAL_MNG_PURCHASE_INVENTORY_EDIT: z.boolean(),
  CHEMICAL_MNG_PURCHASE_INVENTORY_DELETE: z.boolean(),
  CHEMICAL_MNG_TRANSACTION_VIEW: z.boolean(),
  CHEMICAL_MNG_TRANSACTION_CREATE: z.boolean(),
  CHEMICAL_MNG_TRANSACTION_EDIT: z.boolean(),
  CHEMICAL_MNG_TRANSACTION_DELETE: z.boolean(),
  CHEMICAL_MNG_ASSIGNED_TASKS_VIEW: z.boolean(),
  CHEMICAL_MNG_ASSIGNED_TASKS_CREATE: z.boolean(),
  CHEMICAL_MNG_ASSIGNED_TASKS_EDIT: z.boolean(),
  CHEMICAL_MNG_ASSIGNED_TASKS_DELETE: z.boolean(),
  HAZARD_RISK_DASHBOARD_VIEW: z.boolean(),
  HAZARD_RISK_REGISTER_VIEW: z.boolean(),
  HAZARD_RISK_REGISTER_CREATE: z.boolean(),
  HAZARD_RISK_REGISTER_EDIT: z.boolean(),
  HAZARD_RISK_REGISTER_DELETE: z.boolean(),
  HAZARD_RISK_ASSIGNED_TASKS_VIEW: z.boolean(),
  HAZARD_RISK_ASSIGNED_TASKS_CREATE: z.boolean(),
  HAZARD_RISK_ASSIGNED_TASKS_EDIT: z.boolean(),
  HAZARD_RISK_ASSIGNED_TASKS_DELETE: z.boolean(),
  INCIDENT_ACCIDENT_DASHBOARD_VIEW: z.boolean(),
  INCIDENT_ACCIDENT_REGISTER_VIEW: z.boolean(),
  INCIDENT_ACCIDENT_REGISTER_CREATE: z.boolean(),
  INCIDENT_ACCIDENT_REGISTER_EDIT: z.boolean(),
  INCIDENT_ACCIDENT_REGISTER_DELETE: z.boolean(),
  INCIDENT_ACCIDENT_ASSIGNED_TASKS_VIEW: z.boolean(),
  INCIDENT_ACCIDENT_ASSIGNED_TASKS_CREATE: z.boolean(),
  INCIDENT_ACCIDENT_ASSIGNED_TASKS_EDIT: z.boolean(),
  INCIDENT_ACCIDENT_ASSIGNED_TASKS_DELETE: z.boolean(),
  DOCUMENT_REGISTER_VIEW: z.boolean(),
  DOCUMENT_REGISTER_CREATE: z.boolean(),
  DOCUMENT_REGISTER_EDIT: z.boolean(),
  DOCUMENT_REGISTER_DELETE: z.boolean(),
  OCCUPATIONAL_HEALTH_DASHBOARD_VIEW: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PATIENT_REGISTER_VIEW: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PATIENT_REGISTER_CREATE: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PATIENT_REGISTER_EDIT: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PATIENT_REGISTER_DELETE: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_CONSULTATION_VIEW: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_CONSULTATION_CREATE: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_CONSULTATION_EDIT: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_CONSULTATION_DELETE: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_MEDICINE_STOCK_VIEW: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_MEDICINE_STOCK_CREATE: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_MEDICINE_STOCK_EDIT: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_MEDICINE_STOCK_DELETE: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PHARMACY_QUEUE_VIEW: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PHARMACY_QUEUE_CREATE: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PHARMACY_QUEUE_EDIT: z.boolean(),
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PHARMACY_QUEUE_DELETE: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_MEDICINE_REQUEST_VIEW: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_MEDICINE_REQUEST_CREATE: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_MEDICINE_REQUEST_EDIT: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_MEDICINE_REQUEST_DELETE: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_PURCHASE_INVENTORY_VIEW: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_PURCHASE_INVENTORY_CREATE: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_PURCHASE_INVENTORY_EDIT: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_PURCHASE_INVENTORY_DELETE: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_TRANSACTION_VIEW: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_TRANSACTION_CREATE: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_TRANSACTION_EDIT: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_TRANSACTION_DELETE: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_ASSIGNED_TASKS_VIEW: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_ASSIGNED_TASKS_CREATE: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_ASSIGNED_TASKS_EDIT: z.boolean(),
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_ASSIGNED_TASKS_DELETE: z.boolean(),
  GRIEVANCE_DASHBOARD_VIEW: z.boolean(),
  GRIEVANCE_REGISTER_VIEW: z.boolean(),
  GRIEVANCE_REGISTER_CREATE: z.boolean(),
  GRIEVANCE_REGISTER_EDIT: z.boolean(),
  GRIEVANCE_REGISTER_DELETE: z.boolean(),
  GRIEVANCE_ASSIGNED_TASKS_VIEW: z.boolean(),
  GRIEVANCE_ASSIGNED_TASKS_CREATE: z.boolean(),
  GRIEVANCE_ASSIGNED_TASKS_EDIT: z.boolean(),
  GRIEVANCE_ASSIGNED_TASKS_DELETE: z.boolean(),
  RAG_DASHBOARD_VIEW: z.boolean(),
  RAG_REGISTER_VIEW: z.boolean(),
  RAG_REGISTER_CREATE: z.boolean(),
  RAG_REGISTER_EDIT: z.boolean(),
  RAG_REGISTER_DELETE: z.boolean(),
  RAG_ASSIGNED_TASKS_VIEW: z.boolean(),
  RAG_ASSIGNED_TASKS_CREATE: z.boolean(),
  RAG_ASSIGNED_TASKS_EDIT: z.boolean(),
  RAG_ASSIGNED_TASKS_DELETE: z.boolean(),
  ENGAGEMENT_REGISTER_VIEW: z.boolean(),
  ENGAGEMENT_REGISTER_CREATE: z.boolean(),
  ENGAGEMENT_REGISTER_EDIT: z.boolean(),
  ENGAGEMENT_REGISTER_DELETE: z.boolean(),
  ATTRITION_REGISTER: z.boolean(),
  ATTRITION_REGISTER_CREATE: z.boolean(),
  ATTRITION_REGISTER_EDIT: z.boolean(),
  ATTRITION_REGISTER_DELETE: z.boolean(),
});

export type PermissionKeysObject = z.infer<typeof PermissionKeysObjectSchema>;

export const defaultAdminPermissions = {
  INSIGHT_VIEW: true,
  AUDIT_INSPECTION_DASHBOARD_VIEW: true,
  AUDIT_INSPECTION_CALENDAR_VIEW: true,
  AUDIT_INSPECTION_CALENDAR_CREATE: true,
  AUDIT_INSPECTION_CALENDAR_EDIT: true,
  AUDIT_INSPECTION_CALENDAR_DELETE: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_REGISTER_VIEW: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_REGISTER_CREATE: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_REGISTER_EDIT: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_REGISTER_DELETE: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_TASK_VIEW: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_TASK_CREATE: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_TASK_EDIT: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_TASK_DELETE: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_QUEUE_VIEW: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_QUEUE_CREATE: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_QUEUE_EDIT: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_QUEUE_DELETE: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_CORRECTIVE_ACTION_VIEW: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_CORRECTIVE_ACTION_CREATE: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_CORRECTIVE_ACTION_EDIT: true,
  AUDIT_INSPECTION_INTERNAL_AUDIT_CORRECTIVE_ACTION_DELETE: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_REGISTER_VIEW: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_REGISTER_CREATE: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_REGISTER_EDIT: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_REGISTER_DELETE: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_TASK_VIEW: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_TASK_CREATE: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_TASK_EDIT: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_TASK_DELETE: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_QUEUE_VIEW: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_QUEUE_CREATE: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_QUEUE_EDIT: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_QUEUE_DELETE: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_CORRECTIVE_ACTION_VIEW: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_CORRECTIVE_ACTION_CREATE: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_CORRECTIVE_ACTION_EDIT: true,
  AUDIT_INSPECTION_EXTERNAL_AUDIT_CORRECTIVE_ACTION_DELETE: true,
  SUSTAINABILITY_SDG_REPORTING_VIEW: true,
  SUSTAINABILITY_SDG_REPORTING_CREATE: true,
  SUSTAINABILITY_SDG_REPORTING_EDIT: true,
  SUSTAINABILITY_SDG_REPORTING_DELETE: true,
  ENVIRONMENT_DASHBOARD_VIEW: true,
  ENVIRONMENT_HISTORY_CONSUMPTION_VIEW: true,
  ENVIRONMENT_HISTORY_CONSUMPTION_CREATE: true,
  ENVIRONMENT_HISTORY_CONSUMPTION_EDIT: true,
  ENVIRONMENT_HISTORY_CONSUMPTION_DELETE: true,
  ENVIRONMENT_HISTORY_TARGET_SETTING_VIEW: true,
  ENVIRONMENT_HISTORY_TARGET_SETTING_CREATE: true,
  ENVIRONMENT_HISTORY_TARGET_SETTING_EDIT: true,
  ENVIRONMENT_HISTORY_TARGET_SETTING_DELETE: true,
  ENVIRONMENT_ASSIGNED_TASKS_CONSUMPTION_VIEW: true,
  ENVIRONMENT_ASSIGNED_TASKS_CONSUMPTION_CREATE: true,
  ENVIRONMENT_ASSIGNED_TASKS_CONSUMPTION_EDIT: true,
  ENVIRONMENT_ASSIGNED_TASKS_CONSUMPTION_DELETE: true,
  ENVIRONMENT_ASSIGNED_TASKS_TARGET_SETTING_VIEW: true,
  ENVIRONMENT_ASSIGNED_TASKS_TARGET_SETTING_CREATE: true,
  ENVIRONMENT_ASSIGNED_TASKS_TARGET_SETTING_EDIT: true,
  ENVIRONMENT_ASSIGNED_TASKS_TARGET_SETTING_DELETE: true,
  CHEMICAL_MNG_DASHBOARD_VIEW: true,
  CHEMICAL_MNG_REQUEST_REGISTER_VIEW: true,
  CHEMICAL_MNG_REQUEST_REGISTER_CREATE: true,
  CHEMICAL_MNG_REQUEST_REGISTER_EDIT: true,
  CHEMICAL_MNG_REQUEST_REGISTER_DELETE: true,
  CHEMICAL_MNG_PURCHASE_INVENTORY_VIEW: true,
  CHEMICAL_MNG_PURCHASE_INVENTORY_CREATE: true,
  CHEMICAL_MNG_PURCHASE_INVENTORY_EDIT: true,
  CHEMICAL_MNG_PURCHASE_INVENTORY_DELETE: true,
  CHEMICAL_MNG_TRANSACTION_VIEW: true,
  CHEMICAL_MNG_TRANSACTION_CREATE: true,
  CHEMICAL_MNG_TRANSACTION_EDIT: true,
  CHEMICAL_MNG_TRANSACTION_DELETE: true,
  CHEMICAL_MNG_ASSIGNED_TASKS_VIEW: true,
  CHEMICAL_MNG_ASSIGNED_TASKS_CREATE: true,
  CHEMICAL_MNG_ASSIGNED_TASKS_EDIT: true,
  CHEMICAL_MNG_ASSIGNED_TASKS_DELETE: true,
  HAZARD_RISK_DASHBOARD_VIEW: true,
  HAZARD_RISK_REGISTER_VIEW: true,
  HAZARD_RISK_REGISTER_CREATE: true,
  HAZARD_RISK_REGISTER_EDIT: true,
  HAZARD_RISK_REGISTER_DELETE: true,
  HAZARD_RISK_ASSIGNED_TASKS_VIEW: true,
  HAZARD_RISK_ASSIGNED_TASKS_CREATE: true,
  HAZARD_RISK_ASSIGNED_TASKS_EDIT: true,
  HAZARD_RISK_ASSIGNED_TASKS_DELETE: true,
  INCIDENT_ACCIDENT_DASHBOARD_VIEW: true,
  INCIDENT_ACCIDENT_REGISTER_VIEW: true,
  INCIDENT_ACCIDENT_REGISTER_CREATE: true,
  INCIDENT_ACCIDENT_REGISTER_EDIT: true,
  INCIDENT_ACCIDENT_REGISTER_DELETE: true,
  INCIDENT_ACCIDENT_ASSIGNED_TASKS_VIEW: true,
  INCIDENT_ACCIDENT_ASSIGNED_TASKS_CREATE: true,
  INCIDENT_ACCIDENT_ASSIGNED_TASKS_EDIT: true,
  INCIDENT_ACCIDENT_ASSIGNED_TASKS_DELETE: true,
  DOCUMENT_REGISTER_VIEW: true,
  DOCUMENT_REGISTER_CREATE: true,
  DOCUMENT_REGISTER_EDIT: true,
  DOCUMENT_REGISTER_DELETE: true,
  OCCUPATIONAL_HEALTH_DASHBOARD_VIEW: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PATIENT_REGISTER_VIEW: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PATIENT_REGISTER_CREATE: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PATIENT_REGISTER_EDIT: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PATIENT_REGISTER_DELETE: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_CONSULTATION_VIEW: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_CONSULTATION_CREATE: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_CONSULTATION_EDIT: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_CONSULTATION_DELETE: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_MEDICINE_STOCK_VIEW: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_MEDICINE_STOCK_CREATE: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_MEDICINE_STOCK_EDIT: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_MEDICINE_STOCK_DELETE: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PHARMACY_QUEUE_VIEW: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PHARMACY_QUEUE_CREATE: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PHARMACY_QUEUE_EDIT: true,
  OCCUPATIONAL_HEALTH_CLINICAL_SUITE_PHARMACY_QUEUE_DELETE: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_MEDICINE_REQUEST_VIEW: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_MEDICINE_REQUEST_CREATE: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_MEDICINE_REQUEST_EDIT: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_MEDICINE_REQUEST_DELETE: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_PURCHASE_INVENTORY_VIEW: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_PURCHASE_INVENTORY_CREATE: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_PURCHASE_INVENTORY_EDIT: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_PURCHASE_INVENTORY_DELETE: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_TRANSACTION_VIEW: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_TRANSACTION_CREATE: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_TRANSACTION_EDIT: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_TRANSACTION_DELETE: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_ASSIGNED_TASKS_VIEW: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_ASSIGNED_TASKS_CREATE: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_ASSIGNED_TASKS_EDIT: true,
  OCCUPATIONAL_HEALTH_MEDICINE_INVENTORY_ASSIGNED_TASKS_DELETE: true,
  GRIEVANCE_DASHBOARD_VIEW: true,
  GRIEVANCE_REGISTER_VIEW: true,
  GRIEVANCE_REGISTER_CREATE: true,
  GRIEVANCE_REGISTER_EDIT: true,
  GRIEVANCE_REGISTER_DELETE: true,
  GRIEVANCE_ASSIGNED_TASKS_VIEW: true,
  GRIEVANCE_ASSIGNED_TASKS_CREATE: true,
  GRIEVANCE_ASSIGNED_TASKS_EDIT: true,
  GRIEVANCE_ASSIGNED_TASKS_DELETE: true,
  RAG_DASHBOARD_VIEW: true,
  RAG_REGISTER_VIEW: true,
  RAG_REGISTER_CREATE: true,
  RAG_REGISTER_EDIT: true,
  RAG_REGISTER_DELETE: true,
  RAG_ASSIGNED_TASKS_VIEW: true,
  RAG_ASSIGNED_TASKS_CREATE: true,
  RAG_ASSIGNED_TASKS_EDIT: true,
  RAG_ASSIGNED_TASKS_DELETE: true,
  ENGAGEMENT_REGISTER_VIEW: true,
  ENGAGEMENT_REGISTER_CREATE: true,
  ENGAGEMENT_REGISTER_EDIT: true,
  ENGAGEMENT_REGISTER_DELETE: true,
  ATTRITION_REGISTER: true,
  ATTRITION_REGISTER_CREATE: true,
  ATTRITION_REGISTER_EDIT: true,
  ATTRITION_REGISTER_DELETE: true,
};
