import { z } from "zod";

export const ChemicalRequestSchema = z.object({
  id: z.string(),
  request_date: z.date(),
  reference_number: z.string(),
  commercial_name: z.string(),
  substance_name: z.string().optional(),
  formula: z.string().optional(),
  reach_registration_number: z.string().optional(),
  ZDHC_use_category: z.string(),
  usage: z.string(),
  division: z.string(),
  requested_customer: z.string(),
  requested_merchandiser: z.string().optional(),
  status: z.string(),
  modified_date: z.string().nullable(),
  chemical_uuid: z.string(),
  reviewer_remarks: z.string().nullable(),
  approver_remarks: z.string().nullable(),
  reviewer_notification: z.boolean(),
  review_status_notification: z.boolean(),
  approver_notification: z.boolean(),
  approve_status_notification: z.boolean(),
  requested_quantity: z.number(),
  requested_unit: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  publishedAt: z.string(),
  zdhc_level: z.string(),
  cas_no: z.string(),
  colour_index: z.string().optional(),
  use_of_ppe: z.string(),
  hazard_type: z.string(),
  ghs_classification: z.string(),
  chemical_form_type: z.string(),
  product_standard: z.string().optional(),
  msds_sds_issued_date: z.date().nullable(),
  msds_sds_expiry_date: z.date().nullable(),
  msds_sds: z.boolean(),
  created_date: z.string(),
  approval_valid_date: z.date().nullable(),
  category: z.string().nullable(),
  reviewer: z.string(),
  approver: z.string(),
});

export type ChemicalRequest = z.infer<typeof ChemicalRequestSchema>;
